LDFLAGS =
LIBS	=-L/usr/lib -lnsl -lm -lc -lpthread\
	-L/usr/trk45/lib -ltrk \
	-L/usr/FFC/lib -lssl2 -lstd6b
CFLAGS	=-O
INCLUDES=-I/usr/FFC/include \
	-I/usr/trk45/include
FC	=/usr/FFC/bin/frt
CC	=/usr/FFC/bin/fcc
CCP	=/usr/FFC/bin/FCC
TARGET	=tkb32Test
OBJS	=u.o conf.o errno.o rs232c.o netsv.o netcl.o netu.o tm.o weath.o trk.o chop.o fe.o if.o saacq.o tkb32Func.o tkb32Test.o

all:	${TARGET}

${TARGET}: ${OBJS}
	${FC} ${LDFLAGS} -o $@ ${OBJS} ${LIBS}

.cpp.o	:
	${CCP} ${CFLAGS} ${INCLUDES} -c $<
.c.o	:
	${CC} ${CFLAGS} ${INCLUDES} -c $<

u.o	:
	${CCP} ${CFLAGS} ${INCLUDES} -c ../$*/$*.cpp

conf.o	:
	${CCP} ${CFLAGS} ${INCLUDES} -G ../$*/$*.cpp
	${CCP} ${CFLAGS} ${INCLUDES} -c ../$*/$*.cpp

rs232c.o:
	${CCP} ${CFLAGS} ${INCLUDES} -c ../$*/$*.cpp

netsv.o	:
	${CCP} ${CFLAGS} ${INCLUDES} -c ../$*/$*.cpp

netcl.o	:
	${CCP} ${CFLAGS} ${INCLUDES} -c ../$*/$*.cpp

netu.o	:
	${CCP} ${CFLAGS} ${INCLUDES} -c ../$*/$*.cpp

tm.o	:
	${CCP} ${CFLAGS} ${INCLUDES} -c ../$*/$*.cpp


clean   :
	   /bin/rm -f core *.o *.BAK
